# Generated by Django 3.2.9 on 2021-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
