# Generated by Django 3.2.9 on 2021-12-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(to='productos.Categoria'),
        ),
    ]
