# Generated by Django 3.2.9 on 2021-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'INACTIVO'), (3, 'SIN STOCK')], default=1),
        ),
    ]
